package authen

import (
	"github.com/gorilla/securecookie"
	"net/http"
)

var (
	// Generated by securecookie.GenerateRandomKey(64) and (32)
	hashKey  = []byte{144, 70, 174, 35, 6, 213, 43, 118, 83, 230, 186, 64, 107, 144, 8, 112, 176, 2, 0, 88, 81, 226, 52, 100, 242, 56, 45, 57, 221, 60, 129, 68, 63, 214, 63, 85, 59, 229, 119, 144, 48, 246, 218, 149, 198, 172, 95, 50, 1, 152, 94, 238, 9, 114, 62, 55, 87, 35, 54, 164, 119, 125, 245, 85}
	blockKey = []byte{199, 98, 23, 101, 194, 140, 193, 192, 187, 97, 59, 164, 166, 40, 165, 195, 14, 153, 188, 255, 24, 255, 222, 7, 36, 103, 55, 174, 182, 107, 174, 153}
	s        = securecookie.New(hashKey, blockKey)
)

func SetCookie(req http.ResponseWriter, userName string) {
	value := map[string]string{
		"user": userName,
	}
	if encoded, err := s.Encode("session", value); err == nil {
		cookie := &http.Cookie{
			Name:  "session",
			Value: encoded,
			Path:  "/",
		}
		http.SetCookie(req, cookie)
	}
}

func GetUserName(req *http.Request) (userName string) {
	return getCookie(req)["user"]
}

func getCookie(req *http.Request) (value map[string]string) {
	if cookie, err := req.Cookie("session"); err == nil {
		s.Decode("session", cookie.Value, &value)
	}
	return value
}

func ClearCookie(res http.ResponseWriter) {
	cookie := &http.Cookie{
		Name:   "session",
		Value:  "",
		Path:   "/",
		MaxAge: -1,
	}
	http.SetCookie(res, cookie)
}
